# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target 'Glimp' do
pod 'AFNetworking'
pod 'ORStackView'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'HanekeSwift'
pod 'Instabug'
pod 'Refresher'
pod 'SwiftyTimer'

end
