# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target 'Glimp' do
pod 'AFNetworking'
#pod 'ORStackView'
pod 'Alamofire', '~> 3.0'
pod 'HanekeSwift'
pod 'Instabug'
pod 'Refresher'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Bolts'
pod 'FBSDKCoreKit’
pod 'FBSDKShareKit’
pod 'FBSDKLoginKit’
pod 'ActiveLabel'

end
