# Uncomment this line to define a global platform for your project
# platform :ios, "7.0"
source 'https://github.com/CocoaPods/Specs.git'
target "Glimp" do
pod "AFNetworking", "~> 2.0"
pod 'SVProgressHUD', :head
pod 'WYPopoverController', '~> 0.2.2'
pod 'RETableViewManager', '~> 1.5.13'
pod 'CXAlertView'
pod 'QTree-objc'
pod 'Instabug'
pod 'JPSThumbnailAnnotation'
pod 'PHFComposeBarView', '~> 2.0.1'
pod 'KxMenu', '~> 1'
pod 'ViewDeck', '~> 2.3.1'
pod 'CERoundProgressView', '~> 0.0.1'
pod 'SCFacebook'
end

target "GlimpTests" do

end

